name: Deploy Workflow
on: push
jobs:
    buildjob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Install packages
              run: npm install
            - name: Run Lint
              run: yarn run eslint --ext .jsx --fix src
            - name: Test project
              run: vitest run
            - name: Build project
              run: vite build