name: Deploy Workflow
on: push
jobs:
    buildjob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Run Lint
              run: npm run lint
            - name: Test project
              run: npm test
            - name: Build project
              run: npm run build
            - name: Deploy code
              run: echo "Deploying code"